# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: employee.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='employee.proto',
  package='employee.models',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x65mployee.proto\x12\x0f\x65mployee.models\"\xc3\x01\n\x08\x45mployee\x12\x13\n\x0b\x65mployee_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x34\n\x04type\x18\x03 \x01(\x0e\x32&.employee.models.Employee.EmployeeType\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x11\n\textension\x18\x05 \x01(\x05\x12\x0e\n\x06groups\x18\n \x03(\t\",\n\x0c\x45mployeeType\x12\x0e\n\nCONTRACTOR\x10\x00\x12\x0c\n\x08\x46ULLTIME\x10\x01\x62\x06proto3')
)



_EMPLOYEE_EMPLOYEETYPE = _descriptor.EnumDescriptor(
  name='EmployeeType',
  full_name='employee.models.Employee.EmployeeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONTRACTOR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FULLTIME', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=187,
  serialized_end=231,
)
_sym_db.RegisterEnumDescriptor(_EMPLOYEE_EMPLOYEETYPE)


_EMPLOYEE = _descriptor.Descriptor(
  name='Employee',
  full_name='employee.models.Employee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='employee_id', full_name='employee.models.Employee.employee_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='employee.models.Employee.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='employee.models.Employee.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='employee.models.Employee.email', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extension', full_name='employee.models.Employee.extension', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='groups', full_name='employee.models.Employee.groups', index=5,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EMPLOYEE_EMPLOYEETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=231,
)

_EMPLOYEE.fields_by_name['type'].enum_type = _EMPLOYEE_EMPLOYEETYPE
_EMPLOYEE_EMPLOYEETYPE.containing_type = _EMPLOYEE
DESCRIPTOR.message_types_by_name['Employee'] = _EMPLOYEE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Employee = _reflection.GeneratedProtocolMessageType('Employee', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEE,
  '__module__' : 'employee_pb2'
  # @@protoc_insertion_point(class_scope:employee.models.Employee)
  })
_sym_db.RegisterMessage(Employee)


# @@protoc_insertion_point(module_scope)
